# Generated by Django 5.2.12 on 2026-05-30 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produtos", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id_lote",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("validade", models.DateField()),
                ("qtd_lote", models.IntegerField()),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.funcionario",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id_movimentacao",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("entrada", "Entrada"), ("saida", "Saída")],
                        max_length=7,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("reposicao", "Reposição"),
                            ("venda", "Venda"),
                            ("devolucao", "Devolução"),
                            ("vencido", "Produto Vencido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.DateField()),
                ("quantidade", models.IntegerField()),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.funcionario",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="estoque.lote"
                    ),
                ),
            ],
        ),
    ]
