# Generated by Django 5.2.14 on 2026-05-31 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lote",
            old_name="qtd_lote",
            new_name="qtd_item",
        ),
    ]
