# Generated by Django 5.2.12 on 2026-05-30 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nome_cat", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "cod_prod",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nom_produto", models.CharField(max_length=50)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("qtd_item", models.IntegerField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produtos.categoria",
                    ),
                ),
            ],
        ),
    ]
