# Generated by Django 5.2.12 on 2026-05-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "matricula",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=20)),
                ("sobrenome", models.CharField(max_length=20)),
                ("cargo", models.CharField(max_length=50)),
            ],
        ),
    ]
